geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.CategoryProductsReadView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.CategoryProductsReadView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('varify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/geekshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product


def main(request):
    title = 'Магазин'

    products = Product.objects.all()

    context = {
        'title': title,
        'products': products,
    }
    return render(request, 'geekshop/index.html', context)


def contacts(request):
    title = 'Контакты'
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        'title': title,
    }
    return render(request, 'geekshop/contact.html', context)

geekshop/geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="/" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'main' %}" class="{% if request == '/' %}active{% endif %}">домой</a></li>
        <li><a href="{% url 'products:main' %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}">контакты</a></li>
        {% if user.is_authenticated %}
            <li class="dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <a>{{ user.first_name|default:'Пользователь' }}</a>
            </li>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li>
                    <a class="dropdown-item" href="{% url 'auth:edit' %}">
                        Профиль</a>
                </li>
                {% if user.is_superuser %}
                    <li><a class="dropdown-item" href="{% url 'admin_staff:users' %}">Админка</a>
                    </li>
                {% endif %}
                {% if basket %}
                    <li><a class="dropdown-item" href="{% url 'basket:view' %}">Корзина</a>
                    </li>
                {% endif %}
                    <li>
                        {% if user.is_authenticated %}
                            <a href="{% url 'auth:logout' %}">выйти</a>
                        {% endif %}
                    </li>
            </ul>

            {% if basket %}
                <span>
                    {{ basket.0.total_cost|floatformat:0 }} руб.
                    ({{ basket.0.total_quantity }} шт.)
                </span>
            {% endif %}

        {% endif %}
        {% if not user.is_authenticated %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </ul>
    <a href="#" class="search"></a>
</div>

geekshop/geekshop/templates/geekshop/includes/slider.html
<div class="slider">

    {% include 'geekshop/includes/inc_main_menu.html' %}

			<div class="text-slider">
				<h3 class="green">тенденции {% now "Y" %}</h3>
                {% if user.is_authenticated %}
				    <h3 class="big"> удобные стулья</h3>
                {% else %}
                    <h3 class="big"> закончились стулья</h3>
                {% endif %}
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="img/arrow.png" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>